# Generated by Django 5.1.7 on 2025-03-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedimage',
            name='imageRGB',
        ),
        migrations.AddField(
            model_name='processedimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed/%Y/%m/%d/'),
        ),
    ]
